#!/usr/bin/env bash

./install-scripts/symlinks
./install-scripts/homebrew
./install-scripts/go
./install-scripts/hammerspoon
./install-scripts/gems
./install-scripts/ssh
./install-scripts/atom
./install-scripts/terminal
