#!/usr/bin/env bash

dir=$HOME/src/github.com/rickharris/dotfiles
if [ ! -d $dir ]
then
  git clone https://github.com/rickharris/dotfiles.git $dir
fi

$dir/install-scripts/symlinks
$dir/install-scripts/homebrew
$dir/install-scripts/go
$dir/install-scripts/gems
$dir/install-scripts/ssh
$dir/install-scripts/tmux
$dir/install-scripts/iterm2
