#!/usr/bin/env bash
set -e

dir=$HOME/src/github.com/rickharris/dotfiles
if [ ! -d $dir ]; then
	git clone https://github.com/rickharris/dotfiles.git $dir
fi
cd $dir

$dir/install-scripts/symlinks
$dir/install-scripts/ssh
$dir/install-scripts/homebrew
$dir/install-scripts/zsh
$dir/install-scripts/tmux
$dir/install-scripts/iterm2
$dir/install-scripts/keyboard
$dir/install-scripts/node
$dir/install-scripts/dark-mode-notifier
