# True color support
set -ag terminal-overrides ",xterm-256color:RGB"

# Pane base index
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Status line
set-option -g status-position top
set-option -g status-style default
set-option -g status-justify absolute-centre
set-option -g status 2
set-option -g status-format[1]  ""
set-option -g status-left "#[reverse] #S#{?client_prefix, 󰘴 ,}#[default]"
set-option -g status-left-length 50
set-option -g status-right ""
set-option -g window-status-format " #I:#W "
set-option -g window-status-current-format "#[reverse] #I:#W #{?window_zoomed_flag,󰊓 ,}#[default]"
