"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](blue)\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
[╰─](blue)$character"""

add_newline = false

[directory]
style = "fg:blue"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"

[git_branch]
style = 'green'
symbol = ''

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'yellow'

[fill]
symbol = " "

[cmd_duration]
style = 'yellow'

[time]
disabled = false
style = 'cyan'
use_12hr = true
