#!/usr/bin/env bash
set -e

if [ "$SHELL" != "/usr/local/bin/fish" ]; then
  if ! sudo grep -q /usr/local/bin/fish "/etc/shells"; then
    echo '/usr/local/bin/fish' | sudo tee -a /etc/shells
  fi

  chsh -s /usr/local/bin/fish
fi
