#!/usr/bin/env bash
set -e

rbenv install -s 2.6.3
rbenv global 2.6.3

gems=(
  bundler
  rake
  debride
  fasterer
  reek
  rubocop
  ruby-lint
)
for gem in "${gems[@]}"; do
  if test ! $(which $gem)
  then
    echo -e "\nInstalling $gem..."
    gem install $gem
  fi
done
