#!/usr/bin/env bash
set -e

gems=(
  debride
  fasterer
  reek
  rubocop
  ruby-lint
  tmuxinator
)
for gem in "${gems[@]}"; do
  if test ! $(which $gem)
  then
    echo -e "\nInstalling $gem..."
    sudo gem install $gem
  fi
done
