#!/usr/bin/env bash
set -e

rbenv install -s 2.7.3
rbenv global 2.7.3

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

gem install bundler rake

gems=(
  debride
  fasterer
  reek
  rubocop
  ruby-lint
)
for gem in "${gems[@]}"; do
  if test ! $(which $gem)
  then
    echo -e "\nInstalling $gem..."
    gem install $gem
  fi
done
