#!/usr/bin/env bash

if test ! $(which brew)
then
  echo -e "\nInstalling Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo -e "\nInstalling homebrew bundle..."
brew tap Homebrew/bundle
brew bundle

echo -e "\nInstalling python support for neovim..."
pip3 install --upgrade neovim

ln -s /usr/local/bin/nvim /usr/local/bin/vi
ln -s /usr/local/bin/nvim /usr/local/bin/vim
