#!/usr/bin/env bash
set -e

if test ! $(which brew); then
  echo -e "\nInstalling Homebrew…"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  if [[ ! -f $HOME/.zprofile ]]; then
    touch $HOME/.zprofile
  fi
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>/Users/rick/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

echo -e "\nInstalling homebrew dependencies…"
brew tap neovim/neovim
brew install ast-grep \
  bat \
  bash \
  cormacrelf/tap/dark-notify \
  fzf \
  gh \
  git \
  git-delta \
  git-extras \
  gnu-sed \
  go \
  hub \
  jq \
  lazygit \
  neovim \
  python3 \
  ripgrep \
  rust \
  shfmt \
  starship \
  stylua \
  the_silver_searcher \
  tmux \
  wget \
  yarn \
  zplug \
  zsh \
  1password \
  firefox \
  iterm2 \
  visual-studio-code

echo -e "\nInstalling python support for neovim…"
pip3 install --upgrade neovim
