#!/usr/bin/env bash
set -e

if [ ! -d $HOME/.config/lazyvim ]; then
  git clone https://github.com/LazyVim/starter ~/.config/lazyvim
  rm ~/.config/lazyvim/lua/config/lazy.lua
  rm -rf ~/.config/lazyvim/lua/config/plugins/
fi
