#!/usr/bin/env bash
set -e

if [ "$SHELL" != "/usr/local/bin/zsh" ]; then
  if ! sudo grep -q /usr/local/bin/zsh "/etc/shells"; then
    echo '/usr/local/bin/zsh' | sudo tee -a /etc/shells
  fi

  chsh -s /usr/local/bin/zsh
fi
