#!/usr/bin/env bash
set -e

if [ "$SHELL" != "/opt/homebrew/bin/zsh" ]; then
  if ! sudo grep -q /opt/homebrew/bin/zsh "/etc/shells"; then
    echo '/opt/homebrew/bin/zsh' | sudo tee -a /etc/shells
  fi

  chsh -s /opt/homebrew/bin/zsh
fi
